<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Products;
use AppBundle\Entity\Prices;
use AppBundle\Entity\Category;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends EntityRepository
{

	public function addProduct($post)
    {
        $em = $this->getEntityManager();
    	
    	$nomProduit = $post['nom'];
		$stock      = $post['stock'];
		$prices     = $post['prices'];
		$categories = $post['categories'];
		
        $product  = new Products();
        $product->setNom($nomProduit);
        $product->setStock($stock);

		foreach($prices as $key => $value){
			$price = new Prices(); 
			$price->setAmount($value['amount']);
			$price->setCurrency($value['currency']);
			$price->setProduct($product);

			$product->addPrice($price);
			$em->persist($price);
		}

		foreach($categories as $value){
		   $category = $em->getRepository('AppBundle:Category')->find((int)$value);
           $product->addCategory($category);
		}

		$em->persist($product);
		$em->flush();

		$result = array(
			'id'         => $product->getId(),
			'name'       => $product->getNom(),
			'prices'     => $product->getPrices(),
			'stock'      => $product->getStock(),
			'categories' => $product->getCategories()
		);

		return $result;
    } 
}
