app:
    resource: '@AppBundle/Controller/'
    type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

login:
    path: /api/doc/login_check

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
