# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    lexik_jwt_authentication.jwt_token_authenticator:
        class: AppBundle\Security\Guard\JWTTokenAuthenticator
        # parent: lexik_jwt_authentication.security.guard.jwt_token_authenticator
